package com.shinhan.day03;

//try , catch 사용

public class ReferenceTest {
	
	public static void main(String[] args) {
		//call(null);
		call2();
	}

	private static void call2() {
		String s1 = "자바";
		String s2 = "자바";
		String s3 = new String ("자바");
		String s4 = new String ("자바");
		System.out.println(s1==s2?"주소같다":"주소다르다");
		System.out.println(s3==s4?"주소같다":"주소다르다");
		System.out.println(System.identityHashCode(s1));
		System.out.println(System.identityHashCode(s2));
		System.out.println(System.identityHashCode(s3));
		System.out.println(System.identityHashCode(s4));
	}

	private static void call(String s) {
		
		int a = 10; //지역 변수 초기화 -> int a; (X)
		//String s = null; //null은 정의된 값이 없다를 의미한다.
		//String s = "자바";
		
		System.out.println("기본형연습: " + a); //지역변수 초기화 후 사용가능
		System.out.println("참조형연습: " + s); 
		
		try {
			//Exceoption 발생 가능성이 있는 문장들
			System.out.println("참조형연습: " + s.length()); //Null Pointer Exception
		}catch(NullPointerException aa) {
			System.out.println(aa.getMessage());
			System.out.println("null은 정의된 값이 없다를 의미한다. null은 length 불가");
		}
		System.out.println("Exception발생시 프로그램 중단된다. 복구가능");
	}
}
