package com.shinhan.week2.day08.예외처리;

public class ExceptionTest {

	public static void main(String[] args) {
		method1(0);
		method1(10);

	}

	private static void method1(int count) {
		//예외 1)Runtime Exception...실행시 오류 발생 2)일반 Exception
		//1)
		int score = 100;
		int[] arr = new int[10];
		String s = "백";
		
		//if(count==0) return; 
		//비즈니스 로직과 에러확인 로직이 섞여서 권장하지 않음. 
		try {
			System.out.println("평균: " + score/count); //ArithmeticException
			
			arr[9] = 99; //NullPointerException
			
			System.out.println(arr[9]); //ArrayIndexOutOfBoundsException
			
			System.out.println(Integer.parseInt(s) + 200); //NumberFormatException
			
		} catch(ArithmeticException ex) {
			//Exception 처리함....프로그램 중단없이 계속 진행
			System.out.println("연산오류......" + ex.getMessage()); //.getMessage() 오류 메세지 받기
			
		} catch(ArrayIndexOutOfBoundsException ex) {
			//Exception 처리함....프로그램 중단없이 계속 진행
			System.out.println("연산오류......" + ex.getMessage()); //.getMessage() 오류 메세지 받기
			
		} catch(NullPointerException ex) {
			//Exception 처리함....프로그램 중단없이 계속 진행
			System.out.println("연산오류......" + ex.getMessage()); //.getMessage() 오류 메세지 받기
			
		}  catch(NumberFormatException ex) {
			//Exception 처리함....프로그램 중단없이 계속 진행
			System.out.println("연산오류......" + ex.getMessage()); //.getMessage() 오류 메세지 받기
			ex.printStackTrace();
			
		} finally {
			System.out.println("오류가 있거나 없거나 무조건 수행하는 업무(finally)");
			
		}
		System.out.println("--------------------------");
	}

}
